<?php

use Carbon\Carbon;
use Illuminate\Database\Seeder;

class EquipmentSetsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        app('db.connection')->table('equipment_sets')->truncate();
        $data = [
            ['id' => 1, 'name' => "Death's Wind"],
            ['id' => 2, 'name' => "Twilight's Embrace"],
            ['id' => 3, 'name' => "Night's Silence"],
            ['id' => 4, 'name' => "Whitestrake's Retribution"],
            ['id' => 5, 'name' => "Armor of the Seducer"],
            ['id' => 6, 'name' => "Vampire's Kiss"],
            ['id' => 7, 'name' => "Magnus' Gift"],
            ['id' => 8, 'name' => "Night Mother's Gaze"],
            ['id' => 9, 'name' => "Ashen Grip"],
            ['id' => 10, 'name' => "Oblivion's Foe"],
            ['id' => 11, 'name' => "Spectre's Eye"],
            ['id' => 12, 'name' => "Torug's Pact"],
            ['id' => 13, 'name' => "Hist Bark"],
            ['id' => 14, 'name' => "Willow's Path"],
            ['id' => 15, 'name' => "Hunding's Rage"],
            ['id' => 16, 'name' => "Song of Lamae"],
            ['id' => 17, 'name' => "Alessia's Bulwark"],
            ['id' => 18, 'name' => "Orgnum's Scales"],
            ['id' => 19, 'name' => "Eyes of Mara"],
            ['id' => 20, 'name' => "Kagrenac's Hope"],
            ['id' => 21, 'name' => "Shalidor's Curse"],
            ['id' => 22, 'name' => "Way of the Arena"],
            ['id' => 23, 'name' => "The Master's Restoration Staff"],
            ['id' => 24, 'name' => "The Master's Sword"],
            ['id' => 25, 'name' => "The Master's Greatsword"],
            ['id' => 26, 'name' => "The Master's Dagger"],
            ['id' => 27, 'name' => "The Master's Bow"],
            ['id' => 28, 'name' => "The Master's Inferno Staff"],
            ['id' => 29, 'name' => "The Master's Ice Staff"],
            ['id' => 30, 'name' => "The Master's Lightning Staff"],
            ['id' => 31, 'name' => "Twice-Born Star"],
            ['id' => 32, 'name' => "Spawn of Mephala"],
            ['id' => 33, 'name' => "Blood Spawn"],
            ['id' => 34, 'name' => "Lord Warden"],
            ['id' => 35, 'name' => "Scourge Harvester"],
            ['id' => 36, 'name' => "Engine Guardian"],
            ['id' => 37, 'name' => "Nightflame"],
            ['id' => 38, 'name' => "Nerien'eth"],
            ['id' => 39, 'name' => "Valkyn Skoria"],
            ['id' => 40, 'name' => "Maw of the Infernal"],
            ['id' => 41, 'name' => "Noble's Conquest"],
            ['id' => 42, 'name' => "Redistributor"],
            ['id' => 43, 'name' => "Armor Master"],
            ['id' => 44, 'name' => "Molag Kena"],
            ['id' => 45, 'name' => "Black Rose"],
            ['id' => 46, 'name' => "Trinimac's Valor"],
            ['id' => 47, 'name' => "Briarheart"],
            ['id' => 48, 'name' => "Winterborn"],
            ['id' => 49, 'name' => "Powerful Assault"],
            ['id' => 50, 'name' => "Mark of the Pariah"],
            ['id' => 51, 'name' => "Meritorious Service"],
            ['id' => 52, 'name' => "Para Bellum"],
            ['id' => 53, 'name' => "Glorious Defender"],
            ['id' => 54, 'name' => "Elemental Succession"],
            ['id' => 55, 'name' => "Shield Breaker"],
            ['id' => 56, 'name' => "Permafrost"],
            ['id' => 57, 'name' => "Phoenix"],
            ['id' => 58, 'name' => "Hunt Leader"],
            ['id' => 59, 'name' => "Reactive Armor"],
            ['id' => 60, 'name' => "Endurance"],
            ['id' => 61, 'name' => "Willpower"],
            ['id' => 62, 'name' => "Agility"],
            ['id' => 63, 'name' => "Law of Julianos"],
            ['id' => 64, 'name' => "Trial by Fire"],
            ['id' => 65, 'name' => "Morkuldin"],
            ['id' => 66, 'name' => "The Maelstrom's Axe"],
            ['id' => 67, 'name' => "The Maelstrom's Mace"],
            ['id' => 68, 'name' => "The Maelstrom's Sword"],
            ['id' => 69, 'name' => "The Maelstrom's Battle Axe"],
            ['id' => 70, 'name' => "The Maelstrom's Maul"],
            ['id' => 71, 'name' => "The Maelstrom's Greatsword"],
            ['id' => 72, 'name' => "The Maelstrom's Dagger"],
            ['id' => 73, 'name' => "The Maelstrom's Bow"],
            ['id' => 74, 'name' => "The Maelstrom's Inferno Staff"],
            ['id' => 75, 'name' => "The Maelstrom's Ice Staff"],
            ['id' => 76, 'name' => "The Maelstrom's Lightning Staff"],
            ['id' => 77, 'name' => "Tava's Favor"],
            ['id' => 78, 'name' => "Clever Alchemist"],
            ['id' => 79, 'name' => "Eternal Hunt"],
            ['id' => 80, 'name' => "Bahraha's Curse"],
            ['id' => 81, 'name' => "Syvarra's Scales"],
            ['id' => 82, 'name' => "Moondancer"],
            ['id' => 83, 'name' => "Twilight Remedy"],
            ['id' => 84, 'name' => "Roar of Alkosh"],
            ['id' => 85, 'name' => "Lunar Bastion"],
            ['id' => 86, 'name' => "Marksman's Crest"],
            ['id' => 87, 'name' => "Leki's Focus"],
            ['id' => 88, 'name' => "Fasalla's Guile"],
            ['id' => 89, 'name' => "Warrior's Fury"],
            ['id' => 90, 'name' => "Vicious Death"],
            ['id' => 91, 'name' => "Robes of Transmutation"],
            ['id' => 92, 'name' => "Darkstride"],
            ['id' => 93, 'name' => "Shadow Dancer's Raiment"],
            ['id' => 94, 'name' => "Kvatch Gladiator"],
            ['id' => 95, 'name' => "Varen's Legacy"],
            ['id' => 96, 'name' => "Pelinal's Aptitude"],
            ['id' => 97, 'name' => "Hide of Morihaus"],
            ['id' => 98, 'name' => "Flanking Strategist"],
            ['id' => 99, 'name' => "Sithis' Touch"],
            ['id' => 100, 'name' => "Galerion's Revenge"],
            ['id' => 101, 'name' => "Vicecanon of Venom"],
            ['id' => 102, 'name' => "Thews of the Harbinger"],
            ['id' => 103, 'name' => "Imperial Physique"],
            ['id' => 104, 'name' => "The Maelstrom's Restoration Staff"],
            ['id' => 105, 'name' => "Eternal Warrior"],
            ['id' => 106, 'name' => "Vicious Serpent"],
            ['id' => 107, 'name' => "Infallible Mage"],
            ['id' => 108, 'name' => "Queen's Elegance"],
            ['id' => 109, 'name' => "Senche's Bite"],
            ['id' => 110, 'name' => "Velidreth"],
            ['id' => 111, 'name' => "Mighty Chudan"],
            ['id' => 112, 'name' => "Aspect of Mazzatun"],
            ['id' => 113, 'name' => "Amber Plasm"],
            ['id' => 114, 'name' => "Heem-Jas' Retribution"],
            ['id' => 115, 'name' => "Hand of Mephala"],
            ['id' => 116, 'name' => "Gossamer"],
            ['id' => 117, 'name' => "Widowmaker"],
            ['id' => 118, 'name' => "Akaviri Dragonguard"],
            ['id' => 119, 'name' => "Silks of the Sun"],
            ['id' => 120, 'name' => "Shadow of the Red Mountain"],
            ['id' => 121, 'name' => "Syrabane's Grip"],
            ['id' => 122, 'name' => "Salvation"],
            ['id' => 123, 'name' => "Hide of the Werewolf"],
            ['id' => 124, 'name' => "Robes of the Withered Hand"],
            ['id' => 125, 'name' => "Storm Knight's Plate"],
            ['id' => 126, 'name' => "Necropotence"],
            ['id' => 127, 'name' => "Footman's Fortune"],
            ['id' => 128, 'name' => "Healer's Habit"],
            ['id' => 129, 'name' => "Robes of Destruction Mastery"],
            ['id' => 130, 'name' => "Archer's Mind"],
            ['id' => 131, 'name' => "Blessing of the Potentates"],
            ['id' => 132, 'name' => "Deadly Strike"],
            ['id' => 133, 'name' => "Alessian Order"],
            ['id' => 134, 'name' => "Crest of Cyrodiil"],
            ['id' => 135, 'name' => "Bastion of the Heartland"],
            ['id' => 136, 'name' => "Beckoning Steel"],
            ['id' => 137, 'name' => "The Juggernaut"],
            ['id' => 138, 'name' => "Affliction"],
            ['id' => 139, 'name' => "Ravager"],
            ['id' => 140, 'name' => "Elf Bane"],
            ['id' => 141, 'name' => "Wrath of the Imperium"],
            ['id' => 142, 'name' => "Grace of the Ancients"],
            ['id' => 143, 'name' => "Desert Rose"],
            ['id' => 144, 'name' => "Curse Eater"],
            ['id' => 145, 'name' => "Almalexia's Mercy"],
            ['id' => 146, 'name' => "Robes of Alteration Mastery"],
            ['id' => 147, 'name' => "The Arch-Mage"],
            ['id' => 148, 'name' => "Light of Cyrodiil"],
            ['id' => 149, 'name' => "Buffer of the Swift"],
            ['id' => 150, 'name' => "Eagle Eye"],
            ['id' => 151, 'name' => "Vengeance Leech"],
            ['id' => 152, 'name' => "Twin Sisters"],
            ['id' => 153, 'name' => "Shield of the Valiant"],
            ['id' => 154, 'name' => "Shadow Walker"],
            ['id' => 155, 'name' => "Hawk's Eye"],
            ['id' => 156, 'name' => "The Morag Tong"],
            ['id' => 157, 'name' => "Kyne's Kiss"],
            ['id' => 158, 'name' => "Ward of Cyrodiil"],
            ['id' => 159, 'name' => "Sentry"],
            ['id' => 160, 'name' => "Armor of the Veiled Heritance"],
            ['id' => 161, 'name' => "Swarm Mother"],
            ['id' => 162, 'name' => "Slimecraw"],
            ['id' => 163, 'name' => "Tremorscale"],
            ['id' => 164, 'name' => "Pirate Skeleton"],
            ['id' => 165, 'name' => "Shadowrend"],
            ['id' => 166, 'name' => "Sentinel of Rkugamz"],
            ['id' => 167, 'name' => "Chokethorn"],
            ['id' => 168, 'name' => "Infernal Guardian"],
            ['id' => 169, 'name' => "Ilambris"],
            ['id' => 170, 'name' => "Iceheart"],
            ['id' => 171, 'name' => "The Troll King"],
            ['id' => 172, 'name' => "Grothdarr"],
            ['id' => 173, 'name' => "Kra'gh"],
            ['id' => 174, 'name' => "Sellistrix"],
            ['id' => 175, 'name' => "Stormfist"],
            ['id' => 176, 'name' => "Selene"],
            ['id' => 177, 'name' => "Way of Fire"],
            ['id' => 178, 'name' => "Way of Martial Knowledge"],
            ['id' => 179, 'name' => "Way of Air"],
            ['id' => 180, 'name' => "Armor of the Trainee"],
            ['id' => 181, 'name' => "Bloodthorn's Touch"],
            ['id' => 182, 'name' => "Shalk Exoskeleton"],
            ['id' => 183, 'name' => "Wyrd Tree's Blessing"],
            ['id' => 184, 'name' => "Night Mother's Embrace"],
            ['id' => 185, 'name' => "Plague Doctor"],
            ['id' => 186, 'name' => "Mother's Sorrow"],
            ['id' => 187, 'name' => "Wilderqueen's Arch"],
            ['id' => 188, 'name' => "Green Pact"],
            ['id' => 189, 'name' => "Night Terror"],
            ['id' => 190, 'name' => "Dreamer's Mantle"],
            ['id' => 191, 'name' => "Ranger's Gait"],
            ['id' => 192, 'name' => "Beekeeper's Gear"],
            ['id' => 193, 'name' => "Vampire Cloak"],
            ['id' => 194, 'name' => "Robes of the Hist"],
            ['id' => 195, 'name' => "Swamp Raider"],
            ['id' => 196, 'name' => "Hatchling's Shell"],
            ['id' => 197, 'name' => "Sword-Singer"],
            ['id' => 198, 'name' => "Order of Diagna"],
            ['id' => 199, 'name' => "Spinner's Garments"],
            ['id' => 200, 'name' => "Thunderbug's Carapace"],
            ['id' => 201, 'name' => "Stendarr's Embrace"],
            ['id' => 202, 'name' => "Fiord's Legacy"],
            ['id' => 203, 'name' => "Vampire Lord"],
            ['id' => 204, 'name' => "Spriggan's Thorns"],
            ['id' => 205, 'name' => "Seventh Legion Brute"],
            ['id' => 206, 'name' => "Skooma Smuggler"],
            ['id' => 207, 'name' => "Soulshine"],
            ['id' => 208, 'name' => "Ysgramor's Birthright"],
            ['id' => 209, 'name' => "Witchman Armor"],
            ['id' => 210, 'name' => "Draugr's Heritage"],
            ['id' => 211, 'name' => "Prisoner's Rags"],
            ['id' => 212, 'name' => "Stygian"],
            ['id' => 213, 'name' => "Meridia's Blessed Armor"],
            ['id' => 214, 'name' => "Sanctuary"],
            ['id' => 215, 'name' => "Jailbreaker"],
            ['id' => 216, 'name' => "Tormentor"],
            ['id' => 217, 'name' => "Spelunker"],
            ['id' => 218, 'name' => "Spider Cultist Cowl"],
            ['id' => 219, 'name' => "Light Speaker"],
            ['id' => 220, 'name' => "Undaunted Bastion"],
            ['id' => 221, 'name' => "Combat Physician"],
            ['id' => 222, 'name' => "Toothrow"],
            ['id' => 223, 'name' => "Netch's Touch"],
            ['id' => 224, 'name' => "Strength of the Automaton"],
            ['id' => 225, 'name' => "Burning Spellweave"],
            ['id' => 226, 'name' => "Sunderflame"],
            ['id' => 227, 'name' => "Embershield"],
            ['id' => 228, 'name' => "Hircine's Veneer"],
            ['id' => 229, 'name' => "Sword Dancer"],
            ['id' => 230, 'name' => "Treasure Hunter"],
            ['id' => 231, 'name' => "Duneripper's Scales"],
            ['id' => 232, 'name' => "Shroud of the Lich"],
            ['id' => 233, 'name' => "Leviathan"],
            ['id' => 234, 'name' => "Ebon Armory"],
            ['id' => 235, 'name' => "Lamia's Song"],
            ['id' => 236, 'name' => "Undaunted Infiltrator"],
            ['id' => 237, 'name' => "Medusa"],
            ['id' => 238, 'name' => "Magicka Furnace"],
            ['id' => 239, 'name' => "Draugr Hulk"],
            ['id' => 240, 'name' => "Undaunted Unweaver"],
            ['id' => 241, 'name' => "Bone Pirate's Tatters"],
            ['id' => 242, 'name' => "Knight-Errant's Mail"],
            ['id' => 243, 'name' => "Prayer Shawl"],
            ['id' => 244, 'name' => "Knightmare"],
            ['id' => 245, 'name' => "Viper's Sting"],
            ['id' => 246, 'name' => "Dreugh King Slayer"],
            ['id' => 247, 'name' => "Barkskin"],
            ['id' => 248, 'name' => "Sergeant's Mail"],
            ['id' => 249, 'name' => "Armor of Truth"],
            ['id' => 250, 'name' => "Crusader"],
            ['id' => 251, 'name' => "The Ice Furnace"],
            ['id' => 252, 'name' => "Vestments of the Warlock"],
            ['id' => 253, 'name' => "Durok's Bane"],
            ['id' => 254, 'name' => "Noble Duelist's Silks"],
            ['id' => 255, 'name' => "Nikulas' Heavy Armor"],
            ['id' => 256, 'name' => "Overwhelming Surge"],
            ['id' => 257, 'name' => "Storm Master"],
            ['id' => 258, 'name' => "Jolting Arms"],
            ['id' => 259, 'name' => "The Worm's Raiment"],
            ['id' => 260, 'name' => "Oblivion's Edge"],
            ['id' => 261, 'name' => "Rattlecage"],
            ['id' => 262, 'name' => "Scathing Mage"],
            ['id' => 263, 'name' => "Sheer Venom"],
            ['id' => 264, 'name' => "Leeching Plate"],
            ['id' => 265, 'name' => "Spell Power Cure"],
            ['id' => 266, 'name' => "Essence Thief"],
            ['id' => 267, 'name' => "Brands of Imperium"],
            ['id' => 268, 'name' => "Healing Mage"],
            ['id' => 269, 'name' => "Quick Serpent"],
            ['id' => 270, 'name' => "Defending Warrior"],
            ['id' => 271, 'name' => "Destructive Mage"],
            ['id' => 272, 'name' => "Poisonous Serpent"],
            ['id' => 273, 'name' => "Berserking Warrior"],
            ['id' => 274, 'name' => "Wise Mage"],
            ['id' => 275, 'name' => "Twice-Fanged Serpent"],
            ['id' => 276, 'name' => "Immortal Warrior"],
            ['id' => 277, 'name' => "Assassin's Guile"],
            ['id' => 278, 'name' => "Daedric Trickery"],
            ['id' => 279, 'name' => "Shacklebreaker"],
            ['id' => 280, 'name' => "Defiler"],
            ['id' => 281, 'name' => "War Maiden"],
            ['id' => 282, 'name' => "Warrior-Poet"],
            ['id' => 283, 'name' => "Automated Defense"],
            ['id' => 284, 'name' => "Inventor's Guard"],
            ['id' => 285, 'name' => "Master Architect"],
            ['id' => 286, 'name' => "War Machine"],
            ['id' => 287, 'name' => "Coward's Gear"],
            ['id' => 288, 'name' => "Knight Slayer"],
            ['id' => 289, 'name' => "Impregnable Armor"],
            ['id' => 290, 'name' => "Vanguard's Challenge"],
            ['id' => 291, 'name' => "Wizard's Riposte"],
            ['id' => 292, 'name' => "Ironblood"],
            ['id' => 293, 'name' => "Draugr's Rest"],
            ['id' => 294, 'name' => "Pillar of Nirn"],
            ['id' => 295, 'name' => "Hagraven's Garden"],
            ['id' => 296, 'name' => "Flame Blossom"],
            ['id' => 297, 'name' => "Blooddrinker"],
            ['id' => 298, 'name' => "Earthgore"],
            ['id' => 299, 'name' => "Domihaus"],
            ['id' => 300, 'name' => "Innate Axiom"],
            ['id' => 301, 'name' => "Fortified Brass"],
            ['id' => 302, 'name' => "Mechanical Acuity"],
            ['id' => 303, 'name' => "Mad Tinkerer"],
            ['id' => 304, 'name' => "Unfathomable Darkness"],
            ['id' => 305, 'name' => "Livewire"],
            ['id' => 306, 'name' => "Perfect Timeless Blessing"],
            ['id' => 307, 'name' => "Perfect Chaotic Whirlwind"],
            ['id' => 308, 'name' => "Perfect Disciplined Slash"],
            ['id' => 309, 'name' => "Perfect Piercing Spray"],
            ['id' => 310, 'name' => "Perfect Concentrated Force"],
            ['id' => 311, 'name' => "Perfect Defensive Position"],
            ['id' => 312, 'name' => "Timeless Blessing"],
            ['id' => 313, 'name' => "Chaotic Whirlwind"],
            ['id' => 314, 'name' => "Disciplined Slash"],
            ['id' => 315, 'name' => "Piercing Spray"],
            ['id' => 316, 'name' => "Concentrated Force"],
            ['id' => 317, 'name' => "Defensive Position"],
            ['id' => 318, 'name' => "Adept Rider"],
            ['id' => 319, 'name' => "Sload's Semblance"],
            ['id' => 320, 'name' => "Nocturnal's Favor"],
            ['id' => 321, 'name' => "Wisdom of Vanus"],
            ['id' => 322, 'name' => "Gryphon's Ferocity"],
            ['id' => 323, 'name' => "Grace of Gloom"],
            ['id' => 324, 'name' => "Mantle of Siroria"],
            ['id' => 325, 'name' => "Vestment of Olorime"],
            ['id' => 326, 'name' => "Arms of Relequen"],
            ['id' => 327, 'name' => "Aegis of Galenwe"],
            ['id' => 328, 'name' => "Zaan"],
            ['id' => 329, 'name' => "Thurvokun"],
            ['id' => 330, 'name' => "Caluurion's Legacy"],
            ['id' => 331, 'name' => "Jorvuld's Guidance"],
            ['id' => 332, 'name' => "Trappings of Invigoration"],
            ['id' => 333, 'name' => "Plague Slinger"],
            ['id' => 334, 'name' => "Ulfnor's Favor"],
            ['id' => 335, 'name' => "Curse of Doylemish"],
            ['id' => 336, 'name' => "Perfect Aegis of Galenwe"],
            ['id' => 337, 'name' => "Perfect Vestment of Olorime"],
            ['id' => 338, 'name' => "Perfect Arms of Relequen"],
            ['id' => 339, 'name' => "Perfect Mantle of Siroria"],
            ['id' => 340, 'name' => "The Master's Axe"],
            ['id' => 341, 'name' => "Moon Hunter"],
            ['id' => 342, 'name' => "Savage Werewolf"],
            ['id' => 343, 'name' => "Jailer's Tenacity"],
            ['id' => 344, 'name' => "Vykosa"],
            ['id' => 345, 'name' => "Hanu's Compassion"],
            ['id' => 346, 'name' => "Blood Moon"],
            ['id' => 347, 'name' => "Haven of Ursus"],
            ['id' => 348, 'name' => "Balorgh"],
            ['id' => 349, 'name' => "Radial Uppercut"],
            ['id' => 350, 'name' => "Mender's Ward"],
            ['id' => 351, 'name' => "Indomitable Fury"],
            ['id' => 352, 'name' => "Spell Strategist"],
            ['id' => 353, 'name' => "Battlefield Acrobat"],
            ['id' => 354, 'name' => "Soldier of Anguish"],
            ['id' => 355, 'name' => "Steadfast Hero"],
            ['id' => 356, 'name' => "Battalion Defender"],
            ['id' => 357, 'name' => "Bright-Throat's Boast"],
            ['id' => 358, 'name' => "Dead-Water's Guile"],
            ['id' => 359, 'name' => "Champion of the Hist"],
            ['id' => 360, 'name' => "Grave-Stake Collector"],
            ['id' => 361, 'name' => "Naga Shaman"],
            ['id' => 362, 'name' => "Might of the Lost Legion"],
            ['id' => 363, 'name' => "Perfect Radial Uppercut"],
            ['id' => 364, 'name' => "Gallant Charge"],
            ['id' => 365, 'name' => "Perfect Gallant Charge"],
        ];
        app('db.connection')->table('equipment_sets')->insert($data);
        app('db.connection')->table('equipment_sets')->update(['created_at' => Carbon::now()]);
    }
}
