<?php

use Carbon\Carbon;
use Illuminate\Database\Seeder;

class EquipmentSetsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        app('db.connection')->table('equipment_sets')->truncate();

        $data = [
            ['id' => 1, 'slug' => "deaths-wind", 'name' => "Death's Wind"],
            ['id' => 2, 'slug' => "twilights-embrace", 'name' => "Twilight's Embrace"],
            ['id' => 3, 'slug' => "nights-silence", 'name' => "Night's Silence"],
            ['id' => 4, 'slug' => "whitestrakes-retribution", 'name' => "Whitestrake's Retribution"],
            ['id' => 5, 'slug' => "armor-of-the-seducer", 'name' => "Armor of the Seducer"],
            ['id' => 6, 'slug' => "vampires-kiss", 'name' => "Vampire's Kiss"],
            ['id' => 7, 'slug' => "magnus-gift", 'name' => "Magnus' Gift"],
            ['id' => 8, 'slug' => "night-mothers-gaze", 'name' => "Night Mother's Gaze"],
            ['id' => 9, 'slug' => "ashen-grip", 'name' => "Ashen Grip"],
            ['id' => 10, 'slug' => "oblivions-foe", 'name' => "Oblivion's Foe"],
            ['id' => 11, 'slug' => "spectres-eye", 'name' => "Spectre's Eye"],
            ['id' => 12, 'slug' => "torugs-pact", 'name' => "Torug's Pact"],
            ['id' => 13, 'slug' => "hist-bark", 'name' => "Hist Bark"],
            ['id' => 14, 'slug' => "willows-path", 'name' => "Willow's Path"],
            ['id' => 15, 'slug' => "hundings-rage", 'name' => "Hunding's Rage"],
            ['id' => 16, 'slug' => "song-of-lamae", 'name' => "Song of Lamae"],
            ['id' => 17, 'slug' => "alessias-bulwark", 'name' => "Alessia's Bulwark"],
            ['id' => 18, 'slug' => "orgnums-scales", 'name' => "Orgnum's Scales"],
            ['id' => 19, 'slug' => "eyes-of-mara", 'name' => "Eyes of Mara"],
            ['id' => 20, 'slug' => "kagrenacs-hope", 'name' => "Kagrenac's Hope"],
            ['id' => 21, 'slug' => "shalidors-curse", 'name' => "Shalidor's Curse"],
            ['id' => 22, 'slug' => "way-of-the-arena", 'name' => "Way of the Arena"],
            ['id' => 23, 'slug' => "the-masters-restoration-staff", 'name' => "The Master's Restoration Staff"],
            ['id' => 24, 'slug' => "the-masters-sword", 'name' => "The Master's Sword"],
            ['id' => 25, 'slug' => "the-masters-greatsword", 'name' => "The Master's Greatsword"],
            ['id' => 26, 'slug' => "the-masters-dagger", 'name' => "The Master's Dagger"],
            ['id' => 27, 'slug' => "the-masters-bow", 'name' => "The Master's Bow"],
            ['id' => 28, 'slug' => "the-masters-inferno-staff", 'name' => "The Master's Inferno Staff"],
            ['id' => 29, 'slug' => "the-masters-ice-staff", 'name' => "The Master's Ice Staff"],
            ['id' => 30, 'slug' => "the-masters-lightning-staff", 'name' => "The Master's Lightning Staff"],
            ['id' => 31, 'slug' => "twice-born-star", 'name' => "Twice-Born Star"],
            ['id' => 32, 'slug' => "spawn-of-mephala", 'name' => "Spawn of Mephala"],
            ['id' => 33, 'slug' => "blood-spawn", 'name' => "Blood Spawn"],
            ['id' => 34, 'slug' => "lord-warden", 'name' => "Lord Warden"],
            ['id' => 35, 'slug' => "scourge-harvester", 'name' => "Scourge Harvester"],
            ['id' => 36, 'slug' => "engine-guardian", 'name' => "Engine Guardian"],
            ['id' => 37, 'slug' => "nightflame", 'name' => "Nightflame"],
            ['id' => 38, 'slug' => "nerieneth", 'name' => "Nerien'eth"],
            ['id' => 39, 'slug' => "valkyn-skoria", 'name' => "Valkyn Skoria"],
            ['id' => 40, 'slug' => "maw-of-the-infernal", 'name' => "Maw of the Infernal"],
            ['id' => 41, 'slug' => "nobles-conquest", 'name' => "Noble's Conquest"],
            ['id' => 42, 'slug' => "redistributor", 'name' => "Redistributor"],
            ['id' => 43, 'slug' => "armor-master", 'name' => "Armor Master"],
            ['id' => 44, 'slug' => "molag-kena", 'name' => "Molag Kena"],
            ['id' => 45, 'slug' => "black-rose", 'name' => "Black Rose"],
            ['id' => 46, 'slug' => "trinimacs-valor", 'name' => "Trinimac's Valor"],
            ['id' => 47, 'slug' => "briarheart", 'name' => "Briarheart"],
            ['id' => 48, 'slug' => "winterborn", 'name' => "Winterborn"],
            ['id' => 49, 'slug' => "powerful-assault", 'name' => "Powerful Assault"],
            ['id' => 50, 'slug' => "mark-of-the-pariah", 'name' => "Mark of the Pariah"],
            ['id' => 51, 'slug' => "meritorious-service", 'name' => "Meritorious Service"],
            ['id' => 52, 'slug' => "para-bellum", 'name' => "Para Bellum"],
            ['id' => 53, 'slug' => "glorious-defender", 'name' => "Glorious Defender"],
            ['id' => 54, 'slug' => "elemental-succession", 'name' => "Elemental Succession"],
            ['id' => 55, 'slug' => "shield-breaker", 'name' => "Shield Breaker"],
            ['id' => 56, 'slug' => "permafrost", 'name' => "Permafrost"],
            ['id' => 57, 'slug' => "phoenix", 'name' => "Phoenix"],
            ['id' => 58, 'slug' => "hunt-leader", 'name' => "Hunt Leader"],
            ['id' => 59, 'slug' => "reactive-armor", 'name' => "Reactive Armor"],
            ['id' => 60, 'slug' => "endurance", 'name' => "Endurance"],
            ['id' => 61, 'slug' => "willpower", 'name' => "Willpower"],
            ['id' => 62, 'slug' => "agility", 'name' => "Agility"],
            ['id' => 63, 'slug' => "law-of-julianos", 'name' => "Law of Julianos"],
            ['id' => 64, 'slug' => "trial-by-fire", 'name' => "Trial by Fire"],
            ['id' => 65, 'slug' => "morkuldin", 'name' => "Morkuldin"],
            ['id' => 66, 'slug' => "the-maelstroms-axe", 'name' => "The Maelstrom's Axe"],
            ['id' => 67, 'slug' => "the-maelstroms-mace", 'name' => "The Maelstrom's Mace"],
            ['id' => 68, 'slug' => "the-maelstroms-sword", 'name' => "The Maelstrom's Sword"],
            ['id' => 69, 'slug' => "the-maelstroms-battle-axe", 'name' => "The Maelstrom's Battle Axe"],
            ['id' => 70, 'slug' => "the-maelstroms-maul", 'name' => "The Maelstrom's Maul"],
            ['id' => 71, 'slug' => "the-maelstroms-greatsword", 'name' => "The Maelstrom's Greatsword"],
            ['id' => 72, 'slug' => "the-maelstroms-dagger", 'name' => "The Maelstrom's Dagger"],
            ['id' => 73, 'slug' => "the-maelstroms-bow", 'name' => "The Maelstrom's Bow"],
            ['id' => 74, 'slug' => "the-maelstroms-inferno-staff", 'name' => "The Maelstrom's Inferno Staff"],
            ['id' => 75, 'slug' => "the-maelstroms-ice-staff", 'name' => "The Maelstrom's Ice Staff"],
            ['id' => 76, 'slug' => "the-maelstroms-lightning-staff", 'name' => "The Maelstrom's Lightning Staff"],
            ['id' => 77, 'slug' => "tavas-favor", 'name' => "Tava's Favor"],
            ['id' => 78, 'slug' => "clever-alchemist", 'name' => "Clever Alchemist"],
            ['id' => 79, 'slug' => "eternal-hunt", 'name' => "Eternal Hunt"],
            ['id' => 80, 'slug' => "bahrahas-curse", 'name' => "Bahraha's Curse"],
            ['id' => 81, 'slug' => "syvarras-scales", 'name' => "Syvarra's Scales"],
            ['id' => 82, 'slug' => "moondancer", 'name' => "Moondancer"],
            ['id' => 83, 'slug' => "twilight-remedy", 'name' => "Twilight Remedy"],
            ['id' => 84, 'slug' => "roar-of-alkosh", 'name' => "Roar of Alkosh"],
            ['id' => 85, 'slug' => "lunar-bastion", 'name' => "Lunar Bastion"],
            ['id' => 86, 'slug' => "marksmans-crest", 'name' => "Marksman's Crest"],
            ['id' => 87, 'slug' => "lekis-focus", 'name' => "Leki's Focus"],
            ['id' => 88, 'slug' => "fasallas-guile", 'name' => "Fasalla's Guile"],
            ['id' => 89, 'slug' => "warriors-fury", 'name' => "Warrior's Fury"],
            ['id' => 90, 'slug' => "vicious-death", 'name' => "Vicious Death"],
            ['id' => 91, 'slug' => "robes-of-transmutation", 'name' => "Robes of Transmutation"],
            ['id' => 92, 'slug' => "darkstride", 'name' => "Darkstride"],
            ['id' => 93, 'slug' => "shadow-dancers-raiment", 'name' => "Shadow Dancer's Raiment"],
            ['id' => 94, 'slug' => "kvatch-gladiator", 'name' => "Kvatch Gladiator"],
            ['id' => 95, 'slug' => "varens-legacy", 'name' => "Varen's Legacy"],
            ['id' => 96, 'slug' => "pelinals-aptitude", 'name' => "Pelinal's Aptitude"],
            ['id' => 97, 'slug' => "hide-of-morihaus", 'name' => "Hide of Morihaus"],
            ['id' => 98, 'slug' => "flanking-strategist", 'name' => "Flanking Strategist"],
            ['id' => 99, 'slug' => "sithis-touch", 'name' => "Sithis' Touch"],
            ['id' => 100, 'slug' => "galerions-revenge", 'name' => "Galerion's Revenge"],
            ['id' => 101, 'slug' => "vicecanon-of-venom", 'name' => "Vicecanon of Venom"],
            ['id' => 102, 'slug' => "thews-of-the-harbinger", 'name' => "Thews of the Harbinger"],
            ['id' => 103, 'slug' => "imperial-physique", 'name' => "Imperial Physique"],
            ['id' => 104, 'slug' => "the-maelstroms-restoration-staff", 'name' => "The Maelstrom's Restoration Staff"],
            ['id' => 105, 'slug' => "eternal-warrior", 'name' => "Eternal Warrior"],
            ['id' => 106, 'slug' => "vicious-serpent", 'name' => "Vicious Serpent"],
            ['id' => 107, 'slug' => "infallible-mage", 'name' => "Infallible Mage"],
            ['id' => 108, 'slug' => "queens-elegance", 'name' => "Queen's Elegance"],
            ['id' => 109, 'slug' => "senches-bite", 'name' => "Senche's Bite"],
            ['id' => 110, 'slug' => "velidreth", 'name' => "Velidreth"],
            ['id' => 111, 'slug' => "mighty-chudan", 'name' => "Mighty Chudan"],
            ['id' => 112, 'slug' => "aspect-of-mazzatun", 'name' => "Aspect of Mazzatun"],
            ['id' => 113, 'slug' => "amber-plasm", 'name' => "Amber Plasm"],
            ['id' => 114, 'slug' => "heem-jas-retribution", 'name' => "Heem-Jas' Retribution"],
            ['id' => 115, 'slug' => "hand-of-mephala", 'name' => "Hand of Mephala"],
            ['id' => 116, 'slug' => "gossamer", 'name' => "Gossamer"],
            ['id' => 117, 'slug' => "widowmaker", 'name' => "Widowmaker"],
            ['id' => 118, 'slug' => "akaviri-dragonguard", 'name' => "Akaviri Dragonguard"],
            ['id' => 119, 'slug' => "silks-of-the-sun", 'name' => "Silks of the Sun"],
            ['id' => 120, 'slug' => "shadow-of-the-red-mountain", 'name' => "Shadow of the Red Mountain"],
            ['id' => 121, 'slug' => "syrabanes-grip", 'name' => "Syrabane's Grip"],
            ['id' => 122, 'slug' => "salvation", 'name' => "Salvation"],
            ['id' => 123, 'slug' => "hide-of-the-werewolf", 'name' => "Hide of the Werewolf"],
            ['id' => 124, 'slug' => "robes-of-the-withered-hand", 'name' => "Robes of the Withered Hand"],
            ['id' => 125, 'slug' => "storm-knights-plate", 'name' => "Storm Knight's Plate"],
            ['id' => 126, 'slug' => "necropotence", 'name' => "Necropotence"],
            ['id' => 127, 'slug' => "footmans-fortune", 'name' => "Footman's Fortune"],
            ['id' => 128, 'slug' => "healers-habit", 'name' => "Healer's Habit"],
            ['id' => 129, 'slug' => "robes-of-destruction-mastery", 'name' => "Robes of Destruction Mastery"],
            ['id' => 130, 'slug' => "archers-mind", 'name' => "Archer's Mind"],
            ['id' => 131, 'slug' => "blessing-of-the-potentates", 'name' => "Blessing of the Potentates"],
            ['id' => 132, 'slug' => "deadly-strike", 'name' => "Deadly Strike"],
            ['id' => 133, 'slug' => "alessian-order", 'name' => "Alessian Order"],
            ['id' => 134, 'slug' => "crest-of-cyrodiil", 'name' => "Crest of Cyrodiil"],
            ['id' => 135, 'slug' => "bastion-of-the-heartland", 'name' => "Bastion of the Heartland"],
            ['id' => 136, 'slug' => "beckoning-steel", 'name' => "Beckoning Steel"],
            ['id' => 137, 'slug' => "the-juggernaut", 'name' => "The Juggernaut"],
            ['id' => 138, 'slug' => "affliction", 'name' => "Affliction"],
            ['id' => 139, 'slug' => "ravager", 'name' => "Ravager"],
            ['id' => 140, 'slug' => "elf-bane", 'name' => "Elf Bane"],
            ['id' => 141, 'slug' => "wrath-of-the-imperium", 'name' => "Wrath of the Imperium"],
            ['id' => 142, 'slug' => "grace-of-the-ancients", 'name' => "Grace of the Ancients"],
            ['id' => 143, 'slug' => "desert-rose", 'name' => "Desert Rose"],
            ['id' => 144, 'slug' => "curse-eater", 'name' => "Curse Eater"],
            ['id' => 145, 'slug' => "almalexias-mercy", 'name' => "Almalexia's Mercy"],
            ['id' => 146, 'slug' => "robes-of-alteration-mastery", 'name' => "Robes of Alteration Mastery"],
            ['id' => 147, 'slug' => "the-arch-mage", 'name' => "The Arch-Mage"],
            ['id' => 148, 'slug' => "light-of-cyrodiil", 'name' => "Light of Cyrodiil"],
            ['id' => 149, 'slug' => "buffer-of-the-swift", 'name' => "Buffer of the Swift"],
            ['id' => 150, 'slug' => "eagle-eye", 'name' => "Eagle Eye"],
            ['id' => 151, 'slug' => "vengeance-leech", 'name' => "Vengeance Leech"],
            ['id' => 152, 'slug' => "twin-sisters", 'name' => "Twin Sisters"],
            ['id' => 153, 'slug' => "shield-of-the-valiant", 'name' => "Shield of the Valiant"],
            ['id' => 154, 'slug' => "shadow-walker", 'name' => "Shadow Walker"],
            ['id' => 155, 'slug' => "hawks-eye", 'name' => "Hawk's Eye"],
            ['id' => 156, 'slug' => "the-morag-tong", 'name' => "The Morag Tong"],
            ['id' => 157, 'slug' => "kynes-kiss", 'name' => "Kyne's Kiss"],
            ['id' => 158, 'slug' => "ward-of-cyrodiil", 'name' => "Ward of Cyrodiil"],
            ['id' => 159, 'slug' => "sentry", 'name' => "Sentry"],
            ['id' => 160, 'slug' => "armor-of-the-veiled-heritance", 'name' => "Armor of the Veiled Heritance"],
            ['id' => 161, 'slug' => "swarm-mother", 'name' => "Swarm Mother"],
            ['id' => 162, 'slug' => "slimecraw", 'name' => "Slimecraw"],
            ['id' => 163, 'slug' => "tremorscale", 'name' => "Tremorscale"],
            ['id' => 164, 'slug' => "pirate-skeleton", 'name' => "Pirate Skeleton"],
            ['id' => 165, 'slug' => "shadowrend", 'name' => "Shadowrend"],
            ['id' => 166, 'slug' => "sentinel-of-rkugamz", 'name' => "Sentinel of Rkugamz"],
            ['id' => 167, 'slug' => "chokethorn", 'name' => "Chokethorn"],
            ['id' => 168, 'slug' => "infernal-guardian", 'name' => "Infernal Guardian"],
            ['id' => 169, 'slug' => "ilambris", 'name' => "Ilambris"],
            ['id' => 170, 'slug' => "iceheart", 'name' => "Iceheart"],
            ['id' => 171, 'slug' => "the-troll-king", 'name' => "The Troll King"],
            ['id' => 172, 'slug' => "grothdarr", 'name' => "Grothdarr"],
            ['id' => 173, 'slug' => "kragh", 'name' => "Kra'gh"],
            ['id' => 174, 'slug' => "sellistrix", 'name' => "Sellistrix"],
            ['id' => 175, 'slug' => "stormfist", 'name' => "Stormfist"],
            ['id' => 176, 'slug' => "selene", 'name' => "Selene"],
            ['id' => 177, 'slug' => "way-of-fire", 'name' => "Way of Fire"],
            ['id' => 178, 'slug' => "way-of-martial-knowledge", 'name' => "Way of Martial Knowledge"],
            ['id' => 179, 'slug' => "way-of-air", 'name' => "Way of Air"],
            ['id' => 180, 'slug' => "armor-of-the-trainee", 'name' => "Armor of the Trainee"],
            ['id' => 181, 'slug' => "bloodthorns-touch", 'name' => "Bloodthorn's Touch"],
            ['id' => 182, 'slug' => "shalk-exoskeleton", 'name' => "Shalk Exoskeleton"],
            ['id' => 183, 'slug' => "wyrd-trees-blessing", 'name' => "Wyrd Tree's Blessing"],
            ['id' => 184, 'slug' => "night-mothers-embrace", 'name' => "Night Mother's Embrace"],
            ['id' => 185, 'slug' => "plague-doctor", 'name' => "Plague Doctor"],
            ['id' => 186, 'slug' => "mothers-sorrow", 'name' => "Mother's Sorrow"],
            ['id' => 187, 'slug' => "wilderqueens-arch", 'name' => "Wilderqueen's Arch"],
            ['id' => 188, 'slug' => "green-pact", 'name' => "Green Pact"],
            ['id' => 189, 'slug' => "night-terror", 'name' => "Night Terror"],
            ['id' => 190, 'slug' => "dreamers-mantle", 'name' => "Dreamer's Mantle"],
            ['id' => 191, 'slug' => "rangers-gait", 'name' => "Ranger's Gait"],
            ['id' => 192, 'slug' => "beekeepers-gear", 'name' => "Beekeeper's Gear"],
            ['id' => 193, 'slug' => "vampire-cloak", 'name' => "Vampire Cloak"],
            ['id' => 194, 'slug' => "robes-of-the-hist", 'name' => "Robes of the Hist"],
            ['id' => 195, 'slug' => "swamp-raider", 'name' => "Swamp Raider"],
            ['id' => 196, 'slug' => "hatchlings-shell", 'name' => "Hatchling's Shell"],
            ['id' => 197, 'slug' => "sword-singer", 'name' => "Sword-Singer"],
            ['id' => 198, 'slug' => "order-of-diagna", 'name' => "Order of Diagna"],
            ['id' => 199, 'slug' => "spinners-garments", 'name' => "Spinner's Garments"],
            ['id' => 200, 'slug' => "thunderbugs-carapace", 'name' => "Thunderbug's Carapace"],
            ['id' => 201, 'slug' => "stendarrs-embrace", 'name' => "Stendarr's Embrace"],
            ['id' => 202, 'slug' => "fiords-legacy", 'name' => "Fiord's Legacy"],
            ['id' => 203, 'slug' => "vampire-lord", 'name' => "Vampire Lord"],
            ['id' => 204, 'slug' => "spriggans-thorns", 'name' => "Spriggan's Thorns"],
            ['id' => 205, 'slug' => "seventh-legion-brute", 'name' => "Seventh Legion Brute"],
            ['id' => 206, 'slug' => "skooma-smuggler", 'name' => "Skooma Smuggler"],
            ['id' => 207, 'slug' => "soulshine", 'name' => "Soulshine"],
            ['id' => 208, 'slug' => "ysgramors-birthright", 'name' => "Ysgramor's Birthright"],
            ['id' => 209, 'slug' => "witchman-armor", 'name' => "Witchman Armor"],
            ['id' => 210, 'slug' => "draugrs-heritage", 'name' => "Draugr's Heritage"],
            ['id' => 211, 'slug' => "prisoners-rags", 'name' => "Prisoner's Rags"],
            ['id' => 212, 'slug' => "stygian", 'name' => "Stygian"],
            ['id' => 213, 'slug' => "meridias-blessed-armor", 'name' => "Meridia's Blessed Armor"],
            ['id' => 214, 'slug' => "sanctuary", 'name' => "Sanctuary"],
            ['id' => 215, 'slug' => "jailbreaker", 'name' => "Jailbreaker"],
            ['id' => 216, 'slug' => "tormentor", 'name' => "Tormentor"],
            ['id' => 217, 'slug' => "spelunker", 'name' => "Spelunker"],
            ['id' => 218, 'slug' => "spider-cultist-cowl", 'name' => "Spider Cultist Cowl"],
            ['id' => 219, 'slug' => "light-speaker", 'name' => "Light Speaker"],
            ['id' => 220, 'slug' => "undaunted-bastion", 'name' => "Undaunted Bastion"],
            ['id' => 221, 'slug' => "combat-physician", 'name' => "Combat Physician"],
            ['id' => 222, 'slug' => "toothrow", 'name' => "Toothrow"],
            ['id' => 223, 'slug' => "netchs-touch", 'name' => "Netch's Touch"],
            ['id' => 224, 'slug' => "strength-of-the-automaton", 'name' => "Strength of the Automaton"],
            ['id' => 225, 'slug' => "burning-spellweave", 'name' => "Burning Spellweave"],
            ['id' => 226, 'slug' => "sunderflame", 'name' => "Sunderflame"],
            ['id' => 227, 'slug' => "embershield", 'name' => "Embershield"],
            ['id' => 228, 'slug' => "hircines-veneer", 'name' => "Hircine's Veneer"],
            ['id' => 229, 'slug' => "sword-dancer", 'name' => "Sword Dancer"],
            ['id' => 230, 'slug' => "treasure-hunter", 'name' => "Treasure Hunter"],
            ['id' => 231, 'slug' => "dunerippers-scales", 'name' => "Duneripper's Scales"],
            ['id' => 232, 'slug' => "shroud-of-the-lich", 'name' => "Shroud of the Lich"],
            ['id' => 233, 'slug' => "leviathan", 'name' => "Leviathan"],
            ['id' => 234, 'slug' => "ebon-armory", 'name' => "Ebon Armory"],
            ['id' => 235, 'slug' => "lamias-song", 'name' => "Lamia's Song"],
            ['id' => 236, 'slug' => "undaunted-infiltrator", 'name' => "Undaunted Infiltrator"],
            ['id' => 237, 'slug' => "medusa", 'name' => "Medusa"],
            ['id' => 238, 'slug' => "magicka-furnace", 'name' => "Magicka Furnace"],
            ['id' => 239, 'slug' => "draugr-hulk", 'name' => "Draugr Hulk"],
            ['id' => 240, 'slug' => "undaunted-unweaver", 'name' => "Undaunted Unweaver"],
            ['id' => 241, 'slug' => "bone-pirates-tatters", 'name' => "Bone Pirate's Tatters"],
            ['id' => 242, 'slug' => "knight-errants-mail", 'name' => "Knight-Errant's Mail"],
            ['id' => 243, 'slug' => "prayer-shawl", 'name' => "Prayer Shawl"],
            ['id' => 244, 'slug' => "knightmare", 'name' => "Knightmare"],
            ['id' => 245, 'slug' => "vipers-sting", 'name' => "Viper's Sting"],
            ['id' => 246, 'slug' => "dreugh-king-slayer", 'name' => "Dreugh King Slayer"],
            ['id' => 247, 'slug' => "barkskin", 'name' => "Barkskin"],
            ['id' => 248, 'slug' => "sergeants-mail", 'name' => "Sergeant's Mail"],
            ['id' => 249, 'slug' => "armor-of-truth", 'name' => "Armor of Truth"],
            ['id' => 250, 'slug' => "crusader", 'name' => "Crusader"],
            ['id' => 251, 'slug' => "the-ice-furnace", 'name' => "The Ice Furnace"],
            ['id' => 252, 'slug' => "vestments-of-the-warlock", 'name' => "Vestments of the Warlock"],
            ['id' => 253, 'slug' => "duroks-bane", 'name' => "Durok's Bane"],
            ['id' => 254, 'slug' => "noble-duelists-silks", 'name' => "Noble Duelist's Silks"],
            ['id' => 255, 'slug' => "nikulas-heavy-armor", 'name' => "Nikulas' Heavy Armor"],
            ['id' => 256, 'slug' => "overwhelming-surge", 'name' => "Overwhelming Surge"],
            ['id' => 257, 'slug' => "storm-master", 'name' => "Storm Master"],
            ['id' => 258, 'slug' => "jolting-arms", 'name' => "Jolting Arms"],
            ['id' => 259, 'slug' => "the-worms-raiment", 'name' => "The Worm's Raiment"],
            ['id' => 260, 'slug' => "oblivions-edge", 'name' => "Oblivion's Edge"],
            ['id' => 261, 'slug' => "rattlecage", 'name' => "Rattlecage"],
            ['id' => 262, 'slug' => "scathing-mage", 'name' => "Scathing Mage"],
            ['id' => 263, 'slug' => "sheer-venom", 'name' => "Sheer Venom"],
            ['id' => 264, 'slug' => "leeching-plate", 'name' => "Leeching Plate"],
            ['id' => 265, 'slug' => "spell-power-cure", 'name' => "Spell Power Cure"],
            ['id' => 266, 'slug' => "essence-thief", 'name' => "Essence Thief"],
            ['id' => 267, 'slug' => "brands-of-imperium", 'name' => "Brands of Imperium"],
            ['id' => 268, 'slug' => "healing-mage", 'name' => "Healing Mage"],
            ['id' => 269, 'slug' => "quick-serpent", 'name' => "Quick Serpent"],
            ['id' => 270, 'slug' => "defending-warrior", 'name' => "Defending Warrior"],
            ['id' => 271, 'slug' => "destructive-mage", 'name' => "Destructive Mage"],
            ['id' => 272, 'slug' => "poisonous-serpent", 'name' => "Poisonous Serpent"],
            ['id' => 273, 'slug' => "berserking-warrior", 'name' => "Berserking Warrior"],
            ['id' => 274, 'slug' => "wise-mage", 'name' => "Wise Mage"],
            ['id' => 275, 'slug' => "twice-fanged-serpent", 'name' => "Twice-Fanged Serpent"],
            ['id' => 276, 'slug' => "immortal-warrior", 'name' => "Immortal Warrior"],
            ['id' => 277, 'slug' => "assassins-guile", 'name' => "Assassin's Guile"],
            ['id' => 278, 'slug' => "daedric-trickery", 'name' => "Daedric Trickery"],
            ['id' => 279, 'slug' => "shacklebreaker", 'name' => "Shacklebreaker"],
            ['id' => 280, 'slug' => "defiler", 'name' => "Defiler"],
            ['id' => 281, 'slug' => "war-maiden", 'name' => "War Maiden"],
            ['id' => 282, 'slug' => "warrior-poet", 'name' => "Warrior-Poet"],
            ['id' => 283, 'slug' => "automated-defense", 'name' => "Automated Defense"],
            ['id' => 284, 'slug' => "inventors-guard", 'name' => "Inventor's Guard"],
            ['id' => 285, 'slug' => "master-architect", 'name' => "Master Architect"],
            ['id' => 286, 'slug' => "war-machine", 'name' => "War Machine"],
            ['id' => 287, 'slug' => "cowards-gear", 'name' => "Coward's Gear"],
            ['id' => 288, 'slug' => "knight-slayer", 'name' => "Knight Slayer"],
            ['id' => 289, 'slug' => "impregnable-armor", 'name' => "Impregnable Armor"],
            ['id' => 290, 'slug' => "vanguards-challenge", 'name' => "Vanguard's Challenge"],
            ['id' => 291, 'slug' => "wizards-riposte", 'name' => "Wizard's Riposte"],
            ['id' => 292, 'slug' => "ironblood", 'name' => "Ironblood"],
            ['id' => 293, 'slug' => "draugrs-rest", 'name' => "Draugr's Rest"],
            ['id' => 294, 'slug' => "pillar-of-nirn", 'name' => "Pillar of Nirn"],
            ['id' => 295, 'slug' => "hagravens-garden", 'name' => "Hagraven's Garden"],
            ['id' => 296, 'slug' => "flame-blossom", 'name' => "Flame Blossom"],
            ['id' => 297, 'slug' => "blooddrinker", 'name' => "Blooddrinker"],
            ['id' => 298, 'slug' => "earthgore", 'name' => "Earthgore"],
            ['id' => 299, 'slug' => "domihaus", 'name' => "Domihaus"],
            ['id' => 300, 'slug' => "innate-axiom", 'name' => "Innate Axiom"],
            ['id' => 301, 'slug' => "fortified-brass", 'name' => "Fortified Brass"],
            ['id' => 302, 'slug' => "mechanical-acuity", 'name' => "Mechanical Acuity"],
            ['id' => 303, 'slug' => "mad-tinkerer", 'name' => "Mad Tinkerer"],
            ['id' => 304, 'slug' => "unfathomable-darkness", 'name' => "Unfathomable Darkness"],
            ['id' => 305, 'slug' => "livewire", 'name' => "Livewire"],
            ['id' => 306, 'slug' => "perfect-timeless-blessing", 'name' => "Perfect Timeless Blessing"],
            ['id' => 307, 'slug' => "perfect-chaotic-whirlwind", 'name' => "Perfect Chaotic Whirlwind"],
            ['id' => 308, 'slug' => "perfect-disciplined-slash", 'name' => "Perfect Disciplined Slash"],
            ['id' => 309, 'slug' => "perfect-piercing-spray", 'name' => "Perfect Piercing Spray"],
            ['id' => 310, 'slug' => "perfect-concentrated-force", 'name' => "Perfect Concentrated Force"],
            ['id' => 311, 'slug' => "perfect-defensive-position", 'name' => "Perfect Defensive Position"],
            ['id' => 312, 'slug' => "timeless-blessing", 'name' => "Timeless Blessing"],
            ['id' => 313, 'slug' => "chaotic-whirlwind", 'name' => "Chaotic Whirlwind"],
            ['id' => 314, 'slug' => "disciplined-slash", 'name' => "Disciplined Slash"],
            ['id' => 315, 'slug' => "piercing-spray", 'name' => "Piercing Spray"],
            ['id' => 316, 'slug' => "concentrated-force", 'name' => "Concentrated Force"],
            ['id' => 317, 'slug' => "defensive-position", 'name' => "Defensive Position"],
            ['id' => 318, 'slug' => "adept-rider", 'name' => "Adept Rider"],
            ['id' => 319, 'slug' => "sload-s-semblance", 'name' => "Sload's Semblance"],
            ['id' => 320, 'slug' => "nocturnal-s-favor", 'name' => "Nocturnal's Favor"],
            ['id' => 321, 'slug' => "wisdom-of-vanus", 'name' => "Wisdom of Vanus"],
            ['id' => 322, 'slug' => "gryphon-s-ferocity", 'name' => "Gryphon's Ferocity"],
            ['id' => 323, 'slug' => "grace-of-gloom", 'name' => "Grace of Gloom"],
            ['id' => 324, 'slug' => "mantle-of-siroria", 'name' => "Mantle of Siroria"],
            ['id' => 325, 'slug' => "vestment-of-olorime", 'name' => "Vestment of Olorime"],
            ['id' => 326, 'slug' => "arms-of-relequen", 'name' => "Arms of Relequen"],
            ['id' => 327, 'slug' => "aegis-of-galenwe", 'name' => "Aegis of Galenwe"],
            ['id' => 328, 'slug' => "zaan", 'name' => "Zaan"],
            ['id' => 329, 'slug' => "thurvokun", 'name' => "Thurvokun"],
            ['id' => 330, 'slug' => "caluurions-legacy", 'name' => "Caluurion's Legacy"],
            ['id' => 331, 'slug' => "jorvuld-s-guidance", 'name' => "Jorvuld's Guidance"],
            ['id' => 332, 'slug' => "trappings-of-invigoration", 'name' => "Trappings of Invigoration"],
            ['id' => 333, 'slug' => "plague-slinger", 'name' => "Plague Slinger"],
            ['id' => 334, 'slug' => "ulfnor-s-favor", 'name' => "Ulfnor's Favor"],
            ['id' => 335, 'slug' => "curse-of-doylemish", 'name' => "Curse of Doylemish"],
            ['id' => 336, 'slug' => "perfect-aegis-of-galenwe", 'name' => "Perfect Aegis of Galenwe"],
            ['id' => 337, 'slug' => "perfect-vestment-of-olorime", 'name' => "Perfect Vestment of Olorime"],
            ['id' => 338, 'slug' => "perfect-arms-of-relequen", 'name' => "Perfect Arms of Relequen"],
            ['id' => 339, 'slug' => "perfect-mantle-of-siroria", 'name' => "Perfect Mantle of Siroria"],
            ['id' => 340, 'slug' => "the-masters-axe", 'name' => "The Master's Axe"],
            ['id' => 341, 'slug' => "moon-hunter", 'name' => "Moon Hunter"],
            ['id' => 342, 'slug' => "savage-werewolf", 'name' => "Savage Werewolf"],
            ['id' => 343, 'slug' => "jailer-s-tenacity", 'name' => "Jailer's Tenacity"],
            ['id' => 344, 'slug' => "vykosa", 'name' => "Vykosa"],
            ['id' => 345, 'slug' => "hanu-s-compassion", 'name' => "Hanu's Compassion"],
            ['id' => 346, 'slug' => "blood-moon", 'name' => "Blood Moon"],
            ['id' => 347, 'slug' => "haven-of-ursus", 'name' => "Haven of Ursus"],
            ['id' => 348, 'slug' => "balorgh", 'name' => "Balorgh"],
            ['id' => 349, 'slug' => "radial-uppercut", 'name' => "Radial Uppercut"],
            ['id' => 350, 'slug' => "menders-ward", 'name' => "Mender's Ward"],
            ['id' => 351, 'slug' => "indomitable-fury", 'name' => "Indomitable Fury"],
            ['id' => 352, 'slug' => "spell-strategist", 'name' => "Spell Strategist"],
            ['id' => 353, 'slug' => "battlefield-acrobat", 'name' => "Battlefield Acrobat"],
            ['id' => 354, 'slug' => "soldier-of-anguish", 'name' => "Soldier of Anguish"],
            ['id' => 355, 'slug' => "steadfast-hero", 'name' => "Steadfast Hero"],
            ['id' => 356, 'slug' => "battalion-defender", 'name' => "Battalion Defender"],
            ['id' => 357, 'slug' => "bright-throat-s-boast", 'name' => "Bright-Throat's Boast"],
            ['id' => 358, 'slug' => "dead-water-s-guile", 'name' => "Dead-Water's Guile"],
            ['id' => 359, 'slug' => "champion-of-the-hist", 'name' => "Champion of the Hist"],
            ['id' => 360, 'slug' => "grave-stake-collector", 'name' => "Grave-Stake Collector"],
            ['id' => 361, 'slug' => "naga-shaman", 'name' => "Naga Shaman"],
            ['id' => 362, 'slug' => "might-of-the-lost-legion", 'name' => "Might of the Lost Legion"],
            ['id' => 363, 'slug' => "perfect-radial-uppercut", 'name' => "Perfect Radial Uppercut"],
            ['id' => 364, 'slug' => "gallant-charge", 'name' => "Gallant Charge"],
            ['id' => 365, 'slug' => "perfect-gallant-charge", 'name' => "Perfect Gallant Charge"]
        ];
        app('db.connection')->table('equipment_sets')->insert($data);
        app('db.connection')->table('equipment_sets')->update(['created_at' => Carbon::now()]);
    }
}
