branches:
  only:
    - master
    - docker-build

dist: trusty
sudo: required
services:
  - docker

language: php

matrix:
  fast_finish: true
  include:
    - env:
        - DB_CONNECTION=mysql
        - DB_HOST=mariadb
        - DB_USERNAME=root
    - env:
        - DB_CONNECTION=pgsql
        - DB_HOST=postgres
        - DB_USERNAME=postgres

before_install:
  - curl -L https://github.com/docker/compose/releases/download/1.16.1/docker-compose-`uname -s`-`uname -m` > docker-compose; chmod +x docker-compose; true
  - sudo mv docker-compose /usr/local/bin/
  - pwd && docker -v && docker info && docker-compose -v

install:
  - chmod -R 0777 ./storage/logs

#  - export PR=https://api.github.com/repos/$TRAVIS_REPO_SLUG/pulls/$TRAVIS_PULL_REQUEST
#  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo `curl -s $PR | jq -r .head.ref`; fi)
#  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"

  - docker-compose pull;
  - docker-compose up -d;
  - docker images;
  - docker-compose ps;
  - echo $(docker inspect --format='{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' nginx) basis.audith.org | sudo tee -a /etc/hosts;

before_script:
  - chmod +x ./storage/build/scripts/ci/build.sh;

script:
  - ./storage/build/scripts/ci/build.sh;

after_script:
  - docker exec dev /bin/bash -c "pkill sc";
  - if [[ $PHP_VERSION == 7 && $DB_CONNECTION == 'mysql' ]]; then wget https://scrutinizer-ci.com/ocular.phar; php ocular.phar code-coverage:upload --format=php-clover ./storage/coverage/coverage-clover-merged.xml; fi

before_deploy:
  - openssl aes-256-cbc -K $encrypted_7ee790fc7c4a_key -iv $encrypted_7ee790fc7c4a_iv -in deploy_rsa.enc -out deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: ls -l && echo $TRAVIS_BUILD_DIR
  on:
    branch: master
