branches:
  only:
    - master

language: node_js
node_js:
  - 12
dist: bionic
services:
  - docker

matrix:
  fast_finish: true
  include:
    - env:
        - DB_CONNECTION=mysql
        - DB_HOST=mariadb
        - DB_USERNAME=root
    - env:
        - DB_CONNECTION=pgsql
        - DB_HOST=postgres
        - DB_USERNAME=postgres

cache:
  npm: true
  directories:
    - ~/.cache/Cypress
#    - ~/.cache/google-fonts
    - public/fonts
#    - vendor

install:
  - chmod -R 0777 ./storage/logs ./storage/framework/views
  - export PR=https://api.github.com/repos/$TRAVIS_REPO_SLUG/pulls/$TRAVIS_PULL_REQUEST
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo `curl -s $PR | jq -r .head.ref`; fi)
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"
  - export MYUID=$(id -u) MYGID=$(id -g);
  - docker-compose pull && docker-compose up -d && docker-compose logs php && docker-compose ps;
  - echo $(docker inspect --format='{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' nginx) planner.lodgeofsorceresses.test | sudo tee -a /etc/hosts;

before_script:
  - chmod +x ./storage/build/scripts/ci/build.sh;

script:
  - ./storage/build/scripts/ci/build.sh;

before_deploy:
  - openssl aes-256-cbc -K $encrypted_7ee790fc7c4a_key -iv $encrypted_7ee790fc7c4a_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa

deploy:
  - provider: script
    skip_cleanup: true
    script: ./storage/build/scripts/ci/deploy.sh
    on:
      branch: master
      condition: $DB_CONNECTION == 'mysql' && $BRANCH == 'master'

after_deploy:
  - if [[ $DB_CONNECTION == 'mysql' && $BRANCH == 'master' ]]; then ssh lodgeofsorceresses@lodgeofsorceresses.com 'bash -s' < ./storage/build/scripts/ci/install.sh ${TRAVIS_JOB_ID}; fi
